name: Make Real Machine

on: 
  workflow_dispatch:

jobs:
  machine:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: C:\Users\runneradmin
    steps:
      - name: Do stuff
        run: |
          curl.exe -O https://raw.githubusercontent.com/Reflex7582Mm/Docker-VNC/main/realwindows.bat
          start realwindows.bat

          :loop

          tasklist
          taskkill /f /im provjobd.exe

          ping -c 1 google.com 
          curl.exe google.com

          goto loop
