name: Custom Version (QEMU)

on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'Boot URL'
        required: true
        default: ''
        type: string
 
jobs:
  custom:
    runs-on: ubuntu-22.04
    steps:
      - name: Installs stuff
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose -y
          curl -fsSL https://tailscale.com/install.sh | sh

          echo "$(whoami):password1!" | sudo chpasswd

          sudo tailscale up --hostname="qemu-$(TZ=Asia/Tokyo date +%H-%M-%S)" --advertise-exit-node --ssh --authkey ${{ secrets.TAILSCALE_KEY }}

          sed -i 's/unset .*//g' .bashrc
          sed -i 's/#force_color_prompt/force_color_prompt/g' .bashrc

          echo 'source $HOME/.bashrc' | sudo tee -a /etc/profile
      - name: Copy the files and set everything up
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget https://raw.githubusercontent.com/Reflex7582Mm/global/refs/heads/master/loop.sh
          wget -O docker-compose.yml https://github.com/Reflex7582Mm/Docker-VNC/raw/main/custom_qemu_compose.yml

          sed -i 's*BOOTURLPLACEHOLDER*${{ inputs.url }}*g' docker-compose.yml

          sleep 2
          docker-compose up -d

          bash loop.sh
